import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'app.dart';
import 'core/utils/app_bloc_observer.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'injection_container.dart';

void main() async {
  // 1. Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase (Critical for Auth & FCM - Source 4)
  // Note: If you haven't run 'flutterfire configure' yet, comment this out temporarily
  // to run the UI-only version.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Warning: Firebase not initialized. ${e.toString()}");
  }

  // 3. Initialize Dependency Injection (GetIt)
  configureDependencies();

  // 4. Set up BLoC Observer for state logging
  Bloc.observer = AppBlocObserver();

  // 5. Launch the Application
  runApp(const SquadFinderApp());
}